# 检测代码能否正常编译

name: Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build artifact
        run: docker run --rm -v $PWD:/project -w /project espressif/idf:v5.2.1 bash -c "idf.py merge"
      - name: move binary
        run: sudo mv build/esp32s3.bin flash-online/public/esp32s3.bin
      - name: build web
        run: cd flash-online && npm install && npm run build
      - name: build web docker
        run: cd flash-online && docker build -t flash-online .
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./flash-online/dist